# Kumbify SDK Publish Workflow

name: "Kumbify SDK"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # botão para correr manualmente no GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Installating dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publishing
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
