# Kumbify Oficial SDK Workflow publish

name: "Kumbify SDK"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # botão para correr manualmente no GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Installing dependecies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publishing
        run: npm publish --access public --provenance
